---
# tasks file for samh.podman_compose_generator

- name: check required variables
  assert:
    that:
      - podman_compose_generator_user is defined
      - podman_compose_generator_user != ""

# pipx module was added in community.general 3.8.0
# https://github.com/ansible-collections/community.general/pull/3507
- name: install podman-compose using pipx
  when: podman_compose_generator_install_podman_compose
  become: yes
  become_user: "{{ podman_compose_generator_user }}"
  tags: [pipx, install]
  block:
    - name: install podman-compose
      community.general.pipx:
        name: podman-compose

- name: configure podman-compose
  tags: [container, podman, compose]
  become: yes
  become_user: "{{ podman_compose_generator_user }}"
  block:
    - name: deploy podman-compose.yml
      template:
        src: compose.yml.j2
        dest: "{{ podman_compose_generator_compose_file }}"
        owner: "{{ podman_compose_generator_user }}"
        group: "{{ podman_compose_generator_group }}"
        mode: 0600
      notify:
        - restart podman-compose

- name: add podman-compose user service
  tags: [container, podman, compose, systemd]
  become: yes
  become_user: "{{ podman_compose_generator_user }}"
  when: podman_compose_generator_add_service
  block:
    - name: add podman-compose user service
      template:
        src: podman-compose.service.j2
        dest: "{{ podman_compose_generator_service_dir }}/{{ podman_compose_generator_service_name }}.service"
        owner: "{{ podman_compose_generator_user }}"
        group: "{{ podman_compose_generator_group }}"
        mode: 0664
      notify:
        - reload systemd user services
        - restart podman-compose

    - name: configure podman-compose user service
      when: podman_compose_generator_add_service
      ansible.builtin.systemd:
        name: podman-compose
        state: started
        enabled: true
        scope: user
