---
# handlers file for samh.podman_compose_generator
- name: reload systemd user services
  when: podman_compose_generator_add_service
  become: yes
  become_user: "{{ podman_compose_generator_user }}"
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

- name: restart podman-compose
  when: podman_compose_generator_add_service
  become: yes
  become_user: "{{ podman_compose_generator_user }}"
  ansible.builtin.systemd:
    name: "{{ podman_compose_generator_service_name }}"
    state: restarted
    scope: user
